# 运行程序的 Docker 镜像，使用 nodejs 最新稳定版
image: node:lts

# 运行 Job 之前的脚本，安装依赖
before_script:
  - npm install

# Job 名称为 pages 是 Gitlab 约定的，不可修改
pages:
  script:
    # 编译代码，生成产物目录默认为 dist 目录
    - npm run generate
    # 将 dist 目录名修改为 public
    - mv dist public
  artifacts:
    paths:
      - public
  rules:
    # main 分支有更新时自动部署静态网站
    - master
