pages:
  image: node
  before_script:
    - apt-get update && apt-get install -y python3 g++ make
    - corepack enable
    - pnpm install --frozen-lockfile
  script:
    - pnpm generate
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm/
  artifacts:
    paths:
      - .output/public
  publish: .output/public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
