pages:
  image: node:lts
  before_script:
    - corepack enable
    - npm install
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
  variables:
    NITRO_PRESET: gitlab_pages
  script:
    - npm run generate
  artifacts:
    paths:
      - .output/public
  publish: .output/public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
