pages:
  image: node:latest
  before_script:
    - corepack enable
    - npm install
  script:
    - npm run generate --debug
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
  artifacts:
    paths:
      - .output/public
  publish: .output/public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
